# Generated by Django 4.2.27 on 2026-01-30 02:16

import django.db.models.deletion
import django.contrib.postgres.fields
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0994_user_requested_2fa_reset_at"),
        ("tasks", "0020_sandbox_environment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="LLM-generated title describing the detected issue",
                        max_length=255,
                    ),
                ),
                (
                    "task_prompt",
                    models.TextField(help_text="LLM-generated description/prompt for what to fix"),
                ),
                (
                    "cluster_centroid",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        help_text="Embedding centroid for this signal's cluster (3072 dimensions)",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "cluster_centroid_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the cluster centroid was last updated",
                        null=True,
                    ),
                ),
                (
                    "priority_score",
                    models.FloatField(
                        blank=True,
                        help_text="Calculated priority score for ranking signals",
                        null=True,
                    ),
                ),
                (
                    "relevant_user_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of unique users affected by this issue",
                        null=True,
                    ),
                ),
                (
                    "occurrence_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of video segment occurrences",
                        null=True,
                    ),
                ),
                (
                    "last_occurrence_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this issue was last observed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Task created from this signal (if accepted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_signal",
                        to="tasks.task",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="posthog.team",
                    ),
                ),
            ],
            options={
                "db_table": "posthog_signal",
                "ordering": ["-priority_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SignalReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "distinct_id",
                    models.CharField(
                        help_text="The distinct_id of the user who experienced the reference",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The reference description text (what happened in this segment)",
                    ),
                ),
                (
                    "distance_to_centroid",
                    models.FloatField(
                        blank=True,
                        help_text="Cosine distance from this reference to the signal's cluster centroid",
                        null=True,
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="tasks.signal",
                    ),
                ),
            ],
            options={
                "db_table": "posthog_signal_reference",
            },
        ),
        migrations.AddConstraint(
            model_name="signalreference",
            constraint=models.UniqueConstraint(
                fields=("signal_id", "session_id", "start_time", "end_time"),
                name="unique_signal_reference",
            ),
        ),
    ]
